import Banner from '@/components/Banner';
import Card from '@/components/Card';
import Head from 'next/head'
import Layout from '@/components/Layout';
import { InferGetServerSidePropsType } from 'next';
import fetchApi from '../utils/fetchApi'
import { IPost } from '../interfaces'


 const Home = ({ posts }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Layout>
        <Banner/>
        <section className='container mx-auto my-10 px-2 sm:px-'>
          <h3 className="text-4xl font-black text-center my-10">How can we help you?</h3>
          <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-4 gap-1 sm:gap-3">
            {
              posts.map((post: IPost) => (
                <Card key={post.id} post={post}/>
              ))
            }
          </div>
        </section>
      </Layout>
    </>
  )
}
export default Home


export async function getServerSideProps () {
  const graphqlQuery = {
      "operationName": "MyQuery",
      "query": `
      query MyQuery {
        posts {
          id
          content
          title
          category{
            name
          }
          user {
            email
          }
        }
      }  
      `,
      "variables": {}
  };

  const data: any = await fetchApi(graphqlQuery)

  return {
    props: {
      posts: data.data.posts
    },
 };
}